### ISSUE TITLE
Letras y colores 🌼

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/enflujo-two-folded#3]
```css
:root {
  --azulChicle: #10c5f8;
  --moraAzul: #6736dd;
  --amarilloQuemao: #ffea00;
  --rojoPorrazo: #f56468;
  --moradoProfundo: #7a004f;
}
.pareja1 {
  background-color: var(--moraAzul);
  color: var(--azulChicle);
} 

.pareja2 {
  background-color: var(--moradoProfundo);
  color: var(--rojoPorrazo);
} 

.pareja3 {
  background-color: var(--moraAzul);
  color: var(--amarilloQuemao);
} 

.pareja4 {
  background-color: var(--azulProfundo);
  color: var(--rojoPorrazo);
} 
}
```

![0-100](https://github.com/enflujo/enflujo-rastros/assets/42554838/de0f5291-dab2-4596-a276-113e9afd2c91)
![1-100](https://github.com/enflujo/enflujo-rastros/assets/42554838/2cae4ba5-e6ef-4b2a-9838-4272b75663a4)
![2-100](https://github.com/enflujo/enflujo-rastros/assets/42554838/79562e26-1d1e-4aa6-ae10-7270b2a34573)
![4-100](https://github.com/enflujo/enflujo-rastros/assets/42554838/5c409091-5e3e-435e-b9a5-5f9e3236c55b)
